### ISSUE TITLE
[BUG] Varcem creates an empty config.varc file

### ISSUE THREAD

**Issue by Fenix770** [VARCem/VARCem#68]
Hello!

In the last two  or three commints, Varcem creates a config.varc that is empty (0 kb) , so never saves the configuration. The emulator works if I add the config.varc file form an older commit creted in novebember, 2018.

Thanks!

**Comment by waltje** [comment]
Hi,

That is weird!

What do you do to make it do that?

--fred

--------------------------------------------
On Sat, 2/16/19, Fenix770 <notifications@github.com> wrote:

 Subject: [VARCem/VARCem] [BUG] Varcem creates an empty config.varc file (#68)
 To: "VARCem/VARCem" <VARCem@noreply.github.com>
 Cc: "Subscribed" <subscribed@noreply.github.com>
 Date: Saturday, February 16, 2019, 2:10 AM
 
 Hello!
 In the last two  or three commints, Varcem creates a
 config.varc that is empty (0 kb) , so never saves the
 configuration. The emulator works if I add the config.varc
 file form an older commit creted in novebember, 2018.
 Thanks!
 
 —
 You are receiving this because you are subscribed to this
 thread.
 Reply to this email directly, view it on
 GitHub, or mute
 the thread.

**Comment by Fenix770** [comment]
In the old commits from the emulator created the file correctly. In the new ones it always says there is no config file and it creates an empty file.

- The folder is not write protected i checked it .
- I copied the folder to C:\Users\....\Documents\win-336_dev-x86 to see if Win 8.1 interferes in some way  but with same results.

So I think in the last commit something was broken.

Thanks!

**Comment by waltje** [comment]
Fixed in #337, thanks for reporting!
