### ISSUE TITLE
Black screen launching PS/2 Model 50

### ISSUE THREAD

**Issue by Altheos** [VARCem/VARCem#73]
Hi,

build used : latest available 374

Config used : IBM PS/2 Model 50, 286/10, 1 Mo RAM, no timesync, no FPU, internal video, PS/2 mouse, no network, no sound, Parallel port 1 & serial port 1 enabled, MCA ESDI HDD controller, ESDI hard drive, 3 1/2 floppy drive.

black screen at launch :
![image](https://user-images.githubusercontent.com/29195397/56911551-7a954480-6aad-11e9-9356-b0929bf1efc2.png)

**Comment by waltje** [comment]
confirmed, working on it.

**Comment by waltje** [comment]
Fixed.

**Comment by Altheos** [comment]
problem not resolved with latest code source

**Comment by waltje** [comment]
Download and install the current ROMset, and it will be fine.

--fred

--------------------------------------------
On Fri, 5/10/19, Altheos <notifications@github.com> wrote:

 Subject: Re: [VARCem/VARCem] Black screen launching PS/2 Model 50 (#73)
 To: "VARCem/VARCem" <VARCem@noreply.github.com>
 Cc: "Fred N. van Kempen" <decwiz@yahoo.com>, "State change" <state_change@noreply.github.com>
 Date: Friday, May 10, 2019, 4:12 PM
 
 problem not resolved
 with latest code source
 
 —
 You are receiving this because you modified the
 open/close state.
 Reply to this
 email directly, view
 it on GitHub, or mute
 the thread.

**Comment by Altheos** [comment]
Fix confirmed. Thanks !
